apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isutenlandsopphold
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 70
  startup:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 30
  liveness:
    path: /internal/is_alive
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /internal/is_ready
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /internal/metrics
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  ingresses:
    - "https://isutenlandsopphold.intern.dev.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: syfomodiaperson
        - application: syfooversiktsrv
    outbound:
      external:
        - host: "dokarkiv-q2.dev-fss-pub.nais.io"
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "dokdistfordeling.dev-fss-pub.nais.io"
      rules:
        - application: istilgangskontroll
        - application: ispdfgen
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: isutenlandsopphold-db
        diskAutoresize: true
  azure:
    application:
      allowAllUsers: true
      enabled: true
      claims:
        extra:
          - "NAVident"
  kafka:
    pool: nav-dev
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: KTOR_ENV
      value: "production"
    - name: DOKARKIV_URL
      value: "https://dokarkiv-q2.dev-fss-pub.nais.io"
    - name: DOKARKIV_SCOPE
      value: "dev-fss.teamdokumenthandtering.dokarkiv"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "dev-fss.pdl.pdl-api"
    - name: DOKDISTFORDELING_URL
      value: "https://dokdistfordeling.dev-fss-pub.nais.io"
    - name: DOKDISTFORDELING_SCOPE
      value: "dev-fss.teamdokumenthandtering.dokdistfordeling"
    - name: ISPDFGEN_URL
      value: "http://ispdfgen"
    - name: ISTILGANGSKONTROLL_URL
      value: "http://istilgangskontroll"
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: "dev-gcp.teamsykefravr.istilgangskontroll"
    # Skal være false i dev-gcp: mange testbrukere mangler aktør-id i dokarkiv, og vi vil
    # ikke spamme dokarkiv med retries for disse.
    - name: JOURNALFORING_RETRY_ENABLED
      value: "false"
    - name: JOURNALFORING_CRONJOB_INTERVAL_MINUTES
      value: "1"
    - name: KAFKA_SOKNAD_CONSUMER_ENABLED
      value: "true"
